language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build receptor-controller-api-client-ruby.gemspec
  - gem install ./receptor-controller-api-client-ruby-1.0.0.gem
