=begin
#Receptor-Controller

#Receptor-Controller Service

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'date'

module ReceptorControllerApiClientRuby
  class ConnectionStatus
    CONNECTED = "connected".freeze
    DISCONNECTED = "disconnected".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ConnectionStatus.constants.select { |c| ConnectionStatus::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ConnectionStatus" if constantValues.empty?
      value
    end
  end
end
