=begin
#Receptor-Controller

#Receptor-Controller Service

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ReceptorControllerApiClientRuby::ConnectionStatus
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ConnectionStatus' do
  before do
    # run before each test
    @instance = ReceptorControllerApiClientRuby::ConnectionStatus.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ConnectionStatus' do
    it 'should create an instance of ConnectionStatus' do
      expect(@instance).to be_instance_of(ReceptorControllerApiClientRuby::ConnectionStatus)
    end
  end
end
