=begin
#Receptor-Controller

#Receptor-Controller Service

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

# Common files
require 'receptor-controller-api-client-ruby/api_client'
require 'receptor-controller-api-client-ruby/api_error'
require 'receptor-controller-api-client-ruby/version'
require 'receptor-controller-api-client-ruby/configuration'

# Models
require 'receptor-controller-api-client-ruby/models/connection_list_account_response'
require 'receptor-controller-api-client-ruby/models/connection_list_response'
require 'receptor-controller-api-client-ruby/models/connection_list_response_connections'
require 'receptor-controller-api-client-ruby/models/connection_ping_response'
require 'receptor-controller-api-client-ruby/models/connection_status'
require 'receptor-controller-api-client-ruby/models/connection_status_request'
require 'receptor-controller-api-client-ruby/models/connection_status_response'
require 'receptor-controller-api-client-ruby/models/job_request'
require 'receptor-controller-api-client-ruby/models/job_response'
require 'receptor-controller-api-client-ruby/models/payload'

# APIs
require 'receptor-controller-api-client-ruby/api/api_api'

module ReceptorControllerApiClientRuby
  class << self
    # Customize default settings for the SDK using block.
    #   ReceptorControllerApiClientRuby.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
